services:
    - type: web
      name: library-app
      runtime: docker
      plan: free
      region: singapore
      healthCheckPath: /
      envVars:
          - key: APP_ENV
            value: production
          - key: APP_DEBUG
            value: false
          - key: LOG_CHANNEL
            value: stderr
          - key: RUN_MIGRATIONS
            value: true
          - key: SEED_ON_DEPLOY
            value: true
          - key: DB_CONNECTION
            value: pgsql
          - key: DATABASE_URL
            sync: false
          - key: APP_KEY
            generateValue: true
